<!DOCTYPE HTML> <!-- doctype html5 -->
<html lang="en">
<!-- head html -->	
<head>
    <meta charset="UTF-8">
	<?php if (isset($title)): ?> <!-- Si la page a un titr -->
    	<title><?php echo $title; ?></title><!-- alors on l'affiche-->
	<?php else: ?><!--sinon  -->
    	<title>Page Sans titre</title><!-- on lui donne celui la par defaut -->
	<?php endif; ?>
	
	<!-- Ajout des liens des fichiers externes-->
    <link media="all" rel="stylesheet" href="<?php echo base_url('css/blueprint/screen.css'); ?>" type="text/css" />
    <link media="all" rel="stylesheet" href="<?php echo base_url('css/blueprint/print.css'); ?>" type="text/css" />
	
	<link media="all" rel="stylesheet" href="<?php echo base_url('css/style.css'); ?>" type="text/css" />
	
    <script type="text/javascript" src="<?php echo base_url('js/mootools-core.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo base_url('js/mootools-more.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo base_url('js/script.js'); ?>"></script>
</head>
<body>
	<!-- Affichage du contenu lancé par le render-->
    <?php echo $content; ?>
</body>
</html>
