<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
<?php if (isset($title)): ?>
    <title><?php echo $title; ?></title>
<?php else: ?>
    <title>Page Sans titre</title>
<?php endif; ?>
    <link media="all" rel="stylesheet" href="<?php echo base_url('css/blueprint/screen.css'); ?>" type="text/css" />
    <link media="all" rel="stylesheet" href="<?php echo base_url('css/blueprint/print.css'); ?>" type="text/css" />
	
	<link media="all" rel="stylesheet" href="<?php echo base_url('css/style.css'); ?>" type="text/css" />
	
    <script type="text/javascript" src="<?php echo base_url('js/mootools-core.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo base_url('js/mootools-more.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo base_url('js/script.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo base_url('js/scriptColor.js'); ?>"></script>
</head>
<body>

    <?php echo $content; ?>

</body>
</html>
