<!-- Titre de la page -->
<div class="titre">
	<h1>Images Recognizer Similar - Web App</h1><h2>- <?php echo $title; ?></h2>
</div>

<ul> <!-- Bouton retour -->
<li><a href="<?php echo base_url('image'); ?>">Retour</a></li>
</ul>

<?php if ($this->session->flashdata('error')): ?> <!-- Mesage d'erreur -->
	<p class="error">Une erreur est survenue lors de l'édition de cette image.</p>
<?php elseif ($this->session->flashdata('success')): ?> <!-- Message de success -->
	<p class="success">Image éditée avec succès.</p>
<?php endif; ?>

<p>
    <img src="<?php echo base_url('images/' . $image->path . '.jpg'); ?>" alt="Image #<?php echo $image->id; ?>" /> <!-- Lien de l'image a éditer -->
</p>

<!-- <form id="edit" action="<?php echo base_url('image/editPost/' . $image->id); ?>" method="post"> -->
<form id="edit" data-ident='<?php echo $image->id ?>' data-comment='<?php echo $image->comment ?>' method="post">
    <fieldset> <!-- Création du formulaire d'edition -->
        <p>
            <label for="comment">Commentaire :</label> <!-- Texte simple -->
            <input type="text" name="comment" id="comment" value="<?php echo htmlspecialchars($image->comment); ?>" /> 
        </p>

        <p><!-- Bouton edition -->
            <input type="submit" id="btnEdit" value="Modifier l'image" />
        </p>
    </fieldset>
</form>
