<div class="titre">
	<h1>Images Recognizer Similar - Web App</h1><h2>- <?php echo $title; ?></h2>
</div>

<?php if (false !== $imageDestroy = $this->session->flashdata('image_destroy')): ?>
    <?php if ($imageDestroy === "success"): ?>
    <p class="success">L'image a bien été supprimée.</p>
    <?php else: ?>
    <p class="failure">Impossible de supprimer cette image.</p>
    <?php endif; ?>
<?php endif; ?>

<?php if ($error = $this->session->flashdata('error')): ?>
    <p class="failure"><?php echo $error; ?></p>
<?php endif; ?>

<?php $this->load->view('images/search_form.phtml', array('search' => '')); ?>

<ul>
    <li><a href="<?php echo base_url('image/add'); ?>">Ajouter une nouvelle image</a></li>
</ul>

<ul>
    <li class="sort"><a href="<?php echo current_url(); ?>?sortby=id">Trier par ID</a></li><br/>
    <li class="sort"><a href="<?php echo current_url(); ?>?sortby=path">Trier par path</a></li><br/>
    <li class="sort"><a href="<?php echo current_url(); ?>?sortby=comment">Trier par commentaire</a></li>
</ul>

<?php if (isset($pagination)): ?>
<p>Page <?php echo $pagination->cur_page; ?> / <?php echo $total_pages; ?></p>
<?php endif; ?>

<ul>
	<?php $i = 0; ?>
    <?php foreach ($results as $image): ?>
    <li>
        <?php $this->load->view('images/item.phtml', array('image' => $image)); ?>
		 
    </li>
	 <?php if (++$i % 5 == 0): ?>
	 </ul>
	 <ul>
	 <?php endif; ?>
    <?php endforeach; ?>
</ul>

<p>
<?php if (isset($links)): ?>
    <?php echo $links; ?>
    - <a href="<?php echo base_url('image/index/all'); ?>">Tout afficher</a>
<?php else: ?>
    <a href="<?php echo base_url('image/index'); ?>">Afficher par page</a>
<?php endif; ?>
</p>

