<?php
$image_properties = array(
    'src' => base_url('images/' . $image->path . '.jpg'),
    'alt' => 'Image ' . $image->path,
    'class' => "simple_tip",
    'title' => "Image : " . $image->path,
    'rel' => "Commentaire : " . $image->comment,
    'width' => '150',
    'data-id' => $image->id,
    'style' => 'background : white;',
);
?>


<div class="test">
	<?php echo img($image_properties); ?>
	<br />
	<a href="<?php echo base_url('image/show/' . $image->id); ?>" class="view">Show</a>
	- <a href="<?php echo base_url('image/destroy/' . $image->id); ?>">Del</a>
	- <a href="<?php echo base_url('image/edit/' . $image->id); ?>" class="edit">Edit</a>
</div>