<?php
$image_properties = array(
    'src' => base_url('images/' . $image->path . '.jpg'),
    'alt' => 'Image ' . $image->path,
    'class' => "simple_tip",
    'title' => "Image : " . $image->path,
    'rel' => "Commentaire : " . $image->comment,
    'width' => '150',
    'data-id' => $image->id
);
?>
<?php echo img($image_properties); ?>
<p><a href="<?php echo base_url('image/show/' . $image->id); ?>" class="view">Voir</a>
- <a href="<?php echo base_url('image/destroy/' . $image->id); ?>">Supprimer</a>
- <a href="<?php echo base_url('image/edit/' . $image->id); ?>" class="edit">Modifier</a></p>
