<div class="titre">
	<h1>Images Recognizer Similar - Web App</h1><h2>- <?php echo $title; ?></h2>
</div>
<?php $this->load->view('images/search_form.phtml', array('search' => $search)); ?>

<ul>
    <li><a href="<?php echo base_url('image'); ?>">Retour</a></li>
</ul>

<ul>
    <?php foreach ($results as $image): ?>
    <li>
        <?php $this->load->view('images/item.phtml', array('image' => $image)); ?>
    </li>
    <?php endforeach; ?>
</ul>
